dbapp/views/api.py
from flask import Blueprint, jsonify, request
from flask_login import login_required
from flask_principal import Permission, RoleNeed
from dbapp.models.tables import TAGS, TAGSSchema
from sqlalchemy import or_, and_
# from dbapp.file_operation.smb_operation import get_files
from dbapp.file_operation.pdf import PDF_extractor
from dbapp.tools import convertMarkdown

api = Blueprint('api_bp', __name__)

admin_permission = Permission(RoleNeed('Admin'))

@api.route('/tag_search', methods=['GET'])
def tag_search():
    query = request.args.get('query')
    results = TAGS.query.filter(or_(TAGS.name.contains(query), TAGS.tips.contains(query))).all()

    return jsonify({'status': 'ok', 'tagList': TAGSSchema(many=True, exclude=('id', )).dump(results)})

@api.route('/summarize_api', methods=['POST'])
def file_receive():
    pdf = PDF_extractor(request.files['file'])

    return jsonify({"status": "ok", "pubyear":pdf["pubyear"]})


@api.route('/convert', methods=['POST'])
def convert():
    markdown = convertMarkdown(request.form['markdown'])
    return jsonify({"status": "ok", "markdown": markdown})

dbapp/views/user.py
import os, bleach, markdown
from flask import Blueprint, render_template, request, redirect, send_file, abort, session, make_response, url_for, Markup
from flask_paginate import Pagination, get_page_parameter
from flask_login import current_user
from sqlalchemy import desc, not_, func
from datetime import datetime
from dbapp import app, db
from dbapp.models.tables import FILES, TAGS, VOTES, NEWS, STUDIES, FILEACCESS, FILEPREVIEW
from dbapp.tools import convertMarkdown, SearchEngine, FilterStudyFiles, FilterStudiesHiddenFiles
from dbapp.models.tables import FILES, TAGS, VOTES, NEWS, STUDIES, FILEACCESS, FILEPREVIEW, STUDYGRAVES, FILEGRAVES

user_bp = Blueprint('user_bp', __name__, template_folder='templates')

@user_bp.route('/')
def index():
    access_rank = STUDIES.query.join(FILES).filter(STUDIES.grave_data==False).group_by(STUDIES.id).order_by(desc(func.sum(FILES.access_count))).limit(10).all()
    preview_rank = STUDIES.query.join(FILES).filter(STUDIES.grave_data==False).group_by(STUDIES.id).order_by(desc(func.sum(FILES.preview_count))).limit(10).all()
    helpful_rank = db.session.query(
        STUDIES.id,
        STUDIES.name,
        db.func.count(VOTES.study_id),
        db.func.sum(db.case([(VOTES.helpful == True, 1), (VOTES.helpful == False, -1)], else_=0)),
    ).outerjoin(
        VOTES,
        VOTES.study_id == STUDIES.id
    ).filter(
        STUDIES.grave_data==False
    ).group_by(
        STUDIES.id
    ).order_by(
        db.func.sum(db.case([(VOTES.helpful == True, 1), (VOTES.helpful == False, -1)], else_=0)).desc()
    ).limit(10)

    return render_template(
        'user-pages/index.html',
        title='トップページ',
        access_rank=access_rank,
        preview_rank=preview_rank,
        helpful_rank=helpful_rank
    )

@user_bp.route('/taglist')
def taglist():
    tags = TAGS.query.order_by(TAGS.name).all()
    return render_template('user-pages/taglist.html', title="タグ一覧", tags=tags)

@user_bp.route('/study/<id>')
def study(id):
    data = STUDIES.query.filter(STUDIES.id == id).one_or_none()
    if data is None:
        abort(404)

    grave = STUDYGRAVES.query.filter(STUDYGRAVES.study_id==data.id).one_or_none()
    admin = False
    if current_user.is_authenticated:
        admin = current_user.has_role('Admin')
    if grave is not None and not admin:
        return render_template("user-pages/grave.html", title="削除された研究", data=grave), 404

    votes = VOTES.query.filter(VOTES.study_id==data.id)
    helpful_votes = votes.filter(VOTES.helpful==True).count()
    unhelpful_votes = votes.count() - helpful_votes

    if current_user.is_authenticated:
        editable = id in [x.id for x in current_user.studies] or current_user.has_role('Admin')
    else:
        editable = False

    user_vote = None
    if current_user.is_authenticated:
        user_vote = VOTES.query.filter(VOTES.user_id==current_user.id, VOTES.study_id==data.id).one_or_none()

    summary = convertMarkdown(data.raw_markdown)

    return render_template(
        'user-pages/study.html',
        title=data.name,
        data=FilterStudyFiles(data, admin),
        summary=summary,
        helpful_votes=helpful_votes,
        unhelpful_votes=unhelpful_votes,
        user_vote=user_vote,
        editable=editable
    )

@user_bp.route('/file/<id>')
def file(id):
    data = FILES.query.filter(FILES.id == id).one_or_none()
    if data is None:
        abort(404)

    grave = FILEGRAVES.query.filter(FILEGRAVES.file_id==data.id).one_or_none()
    admin = False
    if current_user.is_authenticated:
        admin = current_user.has_role('Admin')
    if grave is not None and not admin:
        return render_template("user-pages/grave.html", title="削除されたファイル", data=grave), 404
    parent_grave = STUDYGRAVES.query.filter(STUDYGRAVES.study_id==data.study_id).one_or_none()
    if parent_grave is not None and not admin:
        return render_template("user-pages/grave.html", title="削除された研究", data=parent_grave), 404


    # セッションにアクセス情報がまだ存在しない場合、アクセス情報をセッションに追加
    if 'accessed_files' not in session:
        session['accessed_files'] = {}

    # ファイルIDがアクセス情報にない場合、アクセスカウントを増加
    if data.id not in session['accessed_files']:
        # ここでアクセスカウントを増加させる操作を行う
        data.access_count += 1
        session['accessed_files'][data.id] = True

        if current_user.is_authenticated:
            # 閲覧履歴を追加
            access_history = FILEACCESS(
                user_id=current_user.id,
                file_id=data.id
            )
            db.session.add(access_history)

        # データベースに変更を保存
        db.session.commit()

    summary = data.summary.split('\n')
    filetypes = ['ポスター発表','プレゼンテーション', '報告書', '要旨', '動画', '画像']
    filetype = filetypes[data.type-1]

    return render_template(
        'user-pages/file.html',
        title=data.name,
        data=data,
        filetype=filetype,
        summary=summary,
    )

@user_bp.route('/file/<id>/preview')
def preview(id):
    data = FILES.query.filter(FILES.id == id).one_or_none()
    if data is None:
        abort(404)

    grave = FILEGRAVES.query.filter(FILEGRAVES.file_id==data.id).one_or_none()
    admin = False
    if current_user.is_authenticated:
        admin = current_user.has_role('Admin')
    if grave is not None and not admin:
        return render_template("user-pages/grave.html", title="削除されたファイル", data=grave), 404

    # セッションにプレビュー情報がまだ存在しない場合、プレビュー情報をセッションに追加
    if 'previewed_files' not in session:
        session['previewed_files'] = {}

    # ファイルIDがプレビュー情報にない場合、プレビューカウントを増加
    if data.id not in session['previewed_files']:
        # ここでプレビューカウントを増加させる操作を行う
        data.preview_count += 1
        session['previewed_files'][data.id] = True

        if current_user.is_authenticated:
            # 閲覧履歴を追加
            previewed_history = FILEPREVIEW(
                user_id=current_user.id,
                file_id=data.id
            )
            db.session.add(previewed_history)

        # データベースに変更を保存
        db.session.commit()
    filepath = os.path.join(app.config['UPLOAD_FOLDER'], data.study.id, data.filename)
    if not os.path.isfile(filepath):
        abort(500)

    file_extension = filepath.split(".")[-1]
    if file_extension == "pdf":
        mimetype = 'application/pdf'
    elif file_extension == "mp4":
        mimetype = 'video/mp4'
    elif file_extension == "png":
        mimetype = 'image/png'

    return make_response(
        send_file(
            filepath,
            as_attachment=False,
            download_name=data.name,
            mimetype=mimetype
        )
    )

@user_bp.route('/news/')
def newslist():
    newslist = NEWS.query.order_by(NEWS.create_at.desc()).all()
    page = request.args.get(get_page_parameter(), type=int, default=1)
    rows = newslist[(page - 1)*10: page*10]
    pagination = Pagination(page=page, total=len(newslist), per_page=10, css_framework="BULMA")

    return render_template('user-pages/newslist.html', title="お知らせ", rows=rows, pagination=pagination)

@user_bp.route('/news/<id>')
def news(id=''):
    news = NEWS.query.filter(NEWS.id==id).one_or_none()
    if news is None:
        abort(404)

    news_text = convertMarkdown(news.raw_markdown)

    title = news.name

    return render_template('user-pages/news.html', title=title, news_text=news_text, news=news)

@user_bp.route('/search', methods=['GET'])
def search():
    raw_query = request.args.get('query', default="")

    create_date_start = request.args.get('create_date_start')
    create_date_start = create_date_start if create_date_start else "0001-01-01"

    create_date_end = request.args.get('create_date_end')
    create_date_end = create_date_end if create_date_end else "9999-12-31"

    update_date_start = request.args.get('update_date_start')
    update_date_start = update_date_start if update_date_start else "0001-01-01"

    update_date_end = request.args.get('update_date_end')
    update_date_end = update_date_end if update_date_end else "9999-12-31"

    field = request.args.get('field', default=0, type=int)

    ascending = request.args.get('ascending', default="True") == "True"
    sort_column = request.args.get('sort_column', default="update_at")

    create_at_range = (datetime.strptime(create_date_start, '%Y-%m-%d'), datetime.strptime(create_date_end, '%Y-%m-%d'))
    update_at_range = (datetime.strptime(update_date_start, '%Y-%m-%d'), datetime.strptime(update_date_end, '%Y-%m-%d'))

    admin = False
    if current_user.is_authenticated:
        admin = current_user.has_role('Admin')

    result_pages = SearchEngine(
        search_terms=raw_query,
        ascending=ascending,
        create_at_range=create_at_range,
        update_at_range=update_at_range,
        sort_column=sort_column,
        field=field,
        admin=admin
    )

    page = request.args.get(get_page_parameter(), type=int, default=1)
    per_page = request.args.get('pp', type=int, default=10)
    rows = result_pages[0][(page - 1)*per_page: page*per_page]
    pagination = Pagination(page=page, total=len(result_pages[0]), per_page=per_page, css_framework="BULMA")

    return render_template(
        'user-pages/search.html',
        title=result_pages[1],
        rows=rows,
        pagination=pagination
    )


@user_bp.route('/tag/<id>')
def tag(id=None):
    if id == '' or id is None:
        return redirect(url_for('user_bp.taglist'))
    else:
        results = TAGS.query.filter(TAGS.id==id).one_or_none()

        if results is None:
            abort(404)
        tips = results.tips.split('\n')
        page = request.args.get(get_page_parameter(), type=int, default=1)
        admin = False
        if current_user.is_authenticated:
            admin = current_user.has_role('Admin')

        filtered_studies = []
        for study in results.studies:
            if study.grave_data == False:
                filtered_studies.append(study)

        results.studies = filtered_studies

        studies = FilterStudiesHiddenFiles(results.studies, admin)

dbapp/templates/user-pages/create_study.html
{% extends "layout.html" %}
{% block content %}

<h2>研究グループの作成</h2>
<form id="form" action="{{ url_for('logined_bp.create_study') }}" method="post" enctype="multipart/form-data">
    {{ form.csrf_token }}
    {{ form.before_title(value="") }}
    <div class="field">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="notification">{{ message }}</div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="field">
            <label class="label">
                タイトル
            </label>
            {% if form.title.errors %}
            {% for error in form.title.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}
            {% endif %}
            <div class="control">
                {{ form.title(class_="input") }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                分野等
            </label>
            <div class="select">
                {{ form.field }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                内容
            </label>
            <div class="columns">
                <div class="column is-half">
                    {{ form.raw_markdown(class_="textarea", rows="10", placeholder="Markdown記法に対応しています")}}
                </div>
                <div class="column is-half">
                    <div id="markdown-preview" class="markdown-container"></div>
                </div>
            </div>
        </div>
        <div class="field">
            <label class="label" data-tooltip="SNSのハッシュタグみたいなもの">
                タグ
            </label>
            <div class="field has-addons">
                <div class="control">
                    <input id="tagBox" class="input">
                </div>
                <div class="control">
                    <a class="button is-primary" id="addBtn">
                        <span class="icon is-small">
                            <i class="material-icons">add</i>
                        </span>
                    </a>
                </div>
                {{ form.tags }}
            </div>
            <div id="tagsfield" class="field is-grouped is-grouped-multiline">
            </div>
            <script>
                $('#tagBox').autocomplete({
                    source: function (request, response) {
                        var suggest = new Array();
                        $.ajax({
                            url: '/api/tag_search',
                            type: 'get',
                            cache: false,
                            dataType: 'json',
                            data: {
                                query: $('#tagBox').val()
                            }
                        }).done(function (res) {
                            for (i of res.tagList) {
                                suggest.push(i.name);
                            };
                            response(suggest);
                        }).fail(function (res) {
                            console.error(res.responseJSON);
                            response([]);
                        });
                    },
                    delay: 200
                });

                jQuery.ui.autocomplete.prototype._resizeMenu = function () {
                    var ul = this.menu.element;
                    ul.outerWidth(this.element.outerWidth());
                }

                function tagAddition(tagtext = '') {
                    if (tagtext == '') {
                        var tagtext = $('#tagBox').val().trim().replace(/[!@#$%^&*()+=\\\[\]{};:?,.\'\"]/g, '_').replace(/ +/g, ' ').replace(/ /g, '_');
                    }
                    if (tagtext != '') {
                        var tagsAmount = $('.tags .tag').length;
                        var tagDeta = '<div class="control"id="tag' + tagsAmount
                            + '"><div class="tags has-addons"><span class="tag" id="tag' + tagsAmount
                            + '">' + tagtext
                            + '</span><a class="tag is-delete" href="javascript:deleteTag('
                            + tagsAmount + ')"></a></div></div>';
                        $('#tagsfield').append(tagDeta);
                        $('#tagBox').val('');
                    };
                }
                $('#addBtn').click(function () {
                    tagAddition();
                });
                $('#tagBox').keydown(function () {
                    $('.ui-menu').width($("#tagBox").width())
                    if (event.keyCode == 13) {
                        tagAddition();
                    }
                });
                function deleteTag(num) {
                    $('#tag' + num).remove();
                };
            </script>
        </div>
        <input value="この内容で追加" type="button" class="button" onclick="addTags()">
    </div>
</form>
<script>
    $(document).ready(function () {
        $('#raw_markdown').on('input', function () {
            $.ajax({
                url: "{{ url_for('api_bp.convert') }}",
                type: 'post',
                cache: false,
                dataType: 'json',
                data: {
                    markdown: $('#raw_markdown').val()
                }
            }).done(function (res) {
                $("#markdown-preview").html(res.markdown);
                $("#summary").val(res.markdown);
            }).fail(function (res) {
                console.error(res.responseJSON);
            });
        });
    });

    function addTags() {
        var tags = [];
        $('#tagsfield .control').each(function () {
            var tag = {};
            tags.push($(this).find('.tag').text());
        });
        $('#tags').val(JSON.stringify(tags));
        $('form').submit()
    };
</script>
{% endblock %}

dbapp/templates/user-pages/filelist.html
{% extends "layout.html" %}
{% block content %}

<h2>{{ title }}</h2>
{{ pagination.info }}
{{ pagination.links }}
{% for result in rows %}
<div class="card">
    <header class="card-header">
        <span class="card-header-icon">
            <span class="icon">
                {% if result.type == 5 %}
                <i class="material-icons">movie</i>
                {% elif result.type ==6 %}
                <i class="material-icons">image</i>
                {% else %}
                <i class="material-icons">picture_as_pdf</i>
                {% endif %}
            </span>
        </span>
        <a class="card-header-title" href="{{ url_for('user_bp.file', id=result.id)}}">
            {{ result.name }}
        </a>
    </header>
    <div class="card-content">
        <div class="content limit-2">
            {{ result.summary }}
        </div>
    </div>
</div>
{% endfor %}
{{ pagination.links }}

{% endblock %}

dbapp/templates/user-pages/grave.html
{% extends "layout.html" %}
{% block content %}

<h2>{{ title }}</h2>
<div class="container">
    <p>
        このファイルは削除されました
    </p>
    <p>
        削除理由: {{ data.reason }}
    </p>
</div>
{% endblock %}

dbapp/templates/user-pages/index.html
{% extends "layout.html" %}
{% block content %}
<div>
    <h2 class="title">アクセス数の多い研究</h2>
    <table class="table">
        <thead>
            <tr>
                <th>順位</th>
                <th>タイトル</th>
                <th>アクセス数</th>
            </tr>
        </thead>
        {% for study in access_rank %}
        <tr>
            <td>{{ loop.index }}</td>
            <td class="limit-1"><a href="{{ url_for('user_bp.study', id = study.id) }}">{{ study.name }}</a></td>
            <td>{{ study.get_total_access_count() }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h2 class="title">プレビュー数の多い研究</h2>
    <table class="table">
        <thead>
            <tr>
                <th>順位</th>
                <th>タイトル</th>
                <th>プレビュー数</th>
            </tr>
        </thead>
        {% for study in preview_rank %}
        <tr>
            <td>{{ loop.index }}</td>
            <td class="limit-1"><a href="{{ url_for('user_bp.study', id = study.id) }}">{{ study.name }}</a></td>
            <td>{{ study.get_total_preview_count() }}</td>
        </tr>
        {% endfor %}
    </table>
</div>
<div>
    <h2 class="title">高く評価されている研究</h2>
    <table class="table">
        <thead>
            <tr>
                <th>順位</th>
                <th>タイトル</th>
            </tr>
        </thead>
        {% for study in helpful_rank %}
        <tr>
            <td>{{ loop.index }}</td>
            <td class="limit-1"><a href="{{ url_for('user_bp.study', id = study.id) }}">{{ study.name }}</a></td>
        </tr>
        {% endfor %}
    </table>
</div>
<!-- <div>
    <h2>タグ登録数ランキング</h2>
    {% for tag in tags %}
    <table>
        <tr>
            <td><a href="/tag?query={{ tag.tag }}">{{ tag.tag }}</a></td>
            <td></td>
        </tr>
    </table>
    {% endfor %}
</div> -->
{% endblock %}

dbapp/templates/user-pages/news.html
{% extends "layout.html" %}
{% block content %}
<h2>{{ title }}</h2>
<p class="has-text-right">
    作成年月日: {{ news.create_at.strftime('%Y年%m月%d日') }}
    <br>
    レコード識別符号: {{ news.id }}
</p>
{{ news_text | safe }}
{% endblock %}

dbapp/templates/user-pages/newslist.html
{% extends "layout.html" %}
{% block content %}
{{ pagination.info }}
{{ pagination.links }}
<ul class="searchResults">
    {% for news in rows %}
    <div class="level">
        <div class="level-left">
            <p class="level-item">
                <h2>
                    <a href="{{ url_for('user_bp.news', id=news.id) }}">
                        {{ news.name }}
                    </a>
                </h2>
            </p>
        </div>
        <div class="level-right">
            <p class="level-item">{{ news.create_at.strftime('%Y年%m月%d日') }}</p>
        </div>
    </div>
    <p class="limit-1">{{ clean_html(convertMarkdown(news.raw_markdown)) }}</p>
    {% endfor %}
</ul>
{{ pagination.links }}
{% endblock %}

dbapp/templates/user-pages/pagelist.html
{% extends "layout.html" %}
{% block content %}
<h2 class="title">{{ title }}</h2>
{% include "user-pages/studylist.html" %}
{% endblock %}

dbapp/templates/user-pages/result_page.html
{% extends "layout.html" %}
{% block content %}
<h2 class="title">アップロード結果</h2>
<table>
    <thead>
        <th>結果</th>
        {% if result["status"] == "failed" %}
        <th>理由</th>
        {% endif %}
        {% if result["status"] == "success" %}
        <th>ページ</th>
        {% endif %}
    </thead>
    <tbody>
        <tr>
            <td>{{ result["status"] }}</td>
            {% if result["status"] == "failed" %}
            <td>{{ result["reason"] }}</td>
            {% endif %}
            {% if result["status"] == "success" %}
            <td><a href="{{ url_for('user_bp.file', id = result['id']) }}">{{ result['name'] }}</a></td>
            {% endif %}
        </tr>
    </tbody>
    <a href="{{ url_for('logined_bp.edit_study', id = result['parent_id']) }}">研究グループの編集に戻る</a>
</table>
{% endblock %}

dbapp/templates/user-pages/result_study.html
{% extends "layout.html" %}
{% block content %}
<h2 class="title">登録結果</h2>
<table>
    <thead>
        <th>結果</th>
        {% if result["status"] == "failed" %}
        <th>理由</th>
        {% endif %}
        {% if result["status"] == "success" %}
        <th>ページ</th>
        {% endif %}
    </thead>
    <tbody>
        <tr>
            <td>{{ result["status"] }}</td>
            {% if result["status"] == "failed" %}
            <td>{{ result["reason"] }}</td>
            {% endif %}
            {% if result["status"] == "success" %}
            <td><a href="{{ url_for('user_bp.study', id = result['id']) }}">{{ result['name'] }}</a></td>
            {% endif %}
        </tr>
    </tbody>
</table>
{% endblock %}

dbapp/templates/user-pages/study.html
{% extends "layout.html" %}
{% block content %}

{% if data.grave_data %}
<div class="notification is-warning">この研究は非公開または削除にされています</div>
{% endif %}
<h2 class="title">{{ data.name }}</h2>
{% if editable %}
<a href="{{ url_for('logined_bp.edit_study', id = data.id)}}" class="button is-primary">この研究を編集する</a>
{% endif %}
<h3 class="title is-4">概要</h3>
<div class="container">
    {{ summary | safe }}
</div>
<div class="container">
    <nav class="panel">
        <p class="panel-heading">
            ファイル一覧
        </p>
        <div class="card-content">
            {% for file in data.files %}
            <a class="panel-block" href="{{ url_for('user_bp.file', id = file.id) }}">
                <div class="columns">
                    <div class="column is-1">
                        <span class="panel-icon">
                            {% if file.type == 5 %}
                            <i class="material-icons">movie</i>
                            {% elif file.type ==6 %}
                            <i class="material-icons">image</i>
                            {% else %}
                            <i class="material-icons">picture_as_pdf</i>
                            {% endif %}
                        </span>
                    </div>
                    <div class="column">
                        <h4>{{ file.name }}</h4>
                        <br>
                        <span class="limit-1">{{ file.summary }}</span>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
    </nav>
</div>
<h3 class="title is-4">詳細情報</h3>
<div class="container">
    <table class="table">
        <thead>
            <tr>
                <th>項目</th>
                <th>内容</th>
            </tr>
        </thead>
        <tr>
            <th>タイトル</th>
            <td>{{ data.name }}</td>
        </tr>
        {% if current_user.is_authenticated %}
        {% if current_user.has_role('Admin') %}
        <tr>
            <th>作成者</th>
            <td>
                <div class="tags">
                    {% for author in data.authors %}
                    <a href="{{ url_for('admin_bp.user_detail', id = author.id) }}" class="tag is-info is-light">{{
                        author.display_name }}</a>
                    {% endfor %}
                </div>
            </td>
        </tr>
        {% endif%}
        {% endif %}
        <tr>
            <th>タグ</th>
            <td>
                <div class="tags">
                    {% for tag in data.tags %}
                    <a href="{{ url_for('user_bp.tag', id = tag.id) }}" class="tag tooltip">
                        {{ tag.name }}
                        <span class="tooltiptext limit-5 box">{{ tag.tips }}</span>
                    </a>
                    {% endfor %}
                </div>
            </td>
        </tr>
        <tr>
            <th>追加日</th>
            <td>{{ data.create_at.strftime('%Y年%m月%d日') }}</td>
        </tr>
        <tr>
            <th>最終更新日</th>
            <td>{{ data.update_at.strftime('%Y年%m月%d日') }}</td>
        </tr>
        <tr>
            <th>分野</th>
            <td>{% if data.field <= 3 %}{{ data.field }}分野{% else %}部活動{% endif %}</td>
        </tr>
        <tr>
            <th>合計プレビュー数</th>
            <td>{{ data.get_total_preview_count() }}</td>
        </tr>
        <tr>
            <th>合計アクセス数</th>
            <td>{{ data.get_total_access_count() }}</td>
        </tr>
        <tr>
            <th>レコード識別符号</th>
            <td>{{ data.id }}</td>
        </tr>
    </table>
    <h3 class="title is-4">この研究は役に立ちましたか?</h3>
    <div class="columns">
        <div class="column is-2">
            <a href="javascript:vote('helpful')" class="button is-primary is-outlined">
                {% if user_vote.helpful is true %}
                <i id="helpful" class="material-icons">thumb_up</i>
                {% else %}
                <i id="helpful" class="material-icons outlined">thumb_up</i>
                {% endif %}
                <span id="helpful_votes">{{ helpful_votes }}</span>
            </a>
        </div>
        <div class="column is-1"></div>
        <div class="column is-2">
            <a href="javascript:vote('unhelpful')" class="button is-warning is-outlined">
                {% if user_vote.helpful is false %}
                <i id="unhelpful" class="material-icons">thumb_down</i>
                {% else %}
                <i id="unhelpful" class="material-icons outlined">thumb_down</i>
                {% endif %}
            </a>
        </div>
        <script>
            function vote(data) {
                var formData = {
                    'helpful': data,
                    'study_id': "{{ data.id }}",
                };
                $.ajax({
                    type: 'POST',
                    url: '/vote',
                    data: JSON.stringify(formData),
                    contentType: 'application/json',
                }).done(function (response, textStatus) {
                    console.log(response);
                    $('#helpful_votes').text(response.helpful);
                    if (response.helpful == true) {
                        $('#helpful').removeClass('outlined');
                        $('#unhelpful').addClass('outlined');
                    } else if (response.helpful == false) {
                        $('#unhelpful').removeClass('outlined');
                        $('#helpful').addClass('outlined');
                    } else {
                        alert("この機能を使うにはログインしてください。");
                    };
                }).fail(function (xhr, textStatus, errorThrown) {
                    console.log("error");
                });
            };
        </script>
    </div>
</div>

{% endblock %}

dbapp/templates/user-pages/tag.html
{% extends "layout.html" %}
{% block content %}
<h2 class="title">{{ results.name }}</h2>
{% for para in tips %}
{{ para }}<br>
{% endfor %}
<br>
レコード識別符号: {{ results.id }}
{% if current_user.is_authenticated %}
{% if current_user.has_role('Admin') %}
<br>
<a href="{{ url_for('admin_bp.edit_tag', id = results.id) }}" class="button is-primary">このタグを編集する</a>
{% endif %}
{% endif %}
<hr>
{% include "user-pages/studylist.html" %}
{% endblock %}